### PR TITLE
Version 1.0.4

### PR DESCRIPTION
**Pull request by lukecarbis**
We're happy with what we've got here!

- Unit tests! :tada: 
- Coveralls
- Various CS fixes
- Dev-lib

@fjarrett Would you please review, and when ready, deploy?

Nice work @marcin-lawrowski and @valendesigns.

### CODE REVIEW

**Comment by fjarrett** [comment]
@lukecarbis Sure, will do this first thing tomorrow. Thanks!

**Comment by valendesigns** [comment]
@lukecarbis I made a quick fix to the `readme.txt` which had some extra whitespace and broke the generated `readme.md`. Please merge that PR into `develop` before @fjarrett begins his review.

Cheers!

**Comment by fjarrett** [comment]
@lukecarbis This is great! Thanks @marcin-lawrowski and @valendesigns for your hard work. Just what I expected from you.

Before I merge, can you help determine if the **Requires at least** version being advertised as 3.5 in the README is indeed accurate?

It would be great if we could add a Travis env for our advertised WP minimum version running only on the minimum PHP version (5.2.4). This way we will know if it ever needs to be bumped due to that particular build failing.

**Comment by valendesigns** [comment]
@fjarrett I've gone ahead and updated `travis.yml` in PR #8 to build with PHP 5.2, 5.6, & 7 which limits the build time and we are also now testing against WP 3.5, latest, and trunk in both single & multisite. The PR just needs to be merged into `develop`.

**Comment by lukecarbis** [comment]
Done.

**Pull request merged**
