### PR TITLE
Make API base URL filterable

### PR DESCRIPTION
**Pull request by fjarrett**
@jonathanbardo Please review.

### CODE REVIEW

**Comment by jonathanbardo** [comment]
@fjarrett Tests are failing

**Comment by fjarrett** [comment]
@jonathanbardo Not because of this branch though.

**Comment by jonathanbardo** [comment]
@fjarrett Really? I thought the goal of this was to make unit tests for this plugin?

**Comment by fjarrett** [comment]
@jonathanbardo I've posted in Slack that I'm looking into the test issue which stemmed from the `develop` branch which is what this branch is forked from, please try to keep up 😉

**Comment by jonathanbardo** [comment]
@fjarrett Information is spreaded! Thanks for the precision.

**Comment by fjarrett** [comment]
Just trying to make progress even though `develop` needs to be repaired. Honestly the test is failing for unknown reasons at the moment. But we will surely get it resolved before anything goes into `master`.

**Comment by jonathanbardo** [comment]
Ok let's merge this and repair the tests on develop.

**Pull request merged**
